# Generated by Django 2.2.26 on 2022-06-12 19:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('maintenanceDate', models.DateField(default=datetime.datetime(2022, 6, 12, 19, 8, 38, 534112))),
                ('mach', models.CharField(choices=[('PC', 'PC - windows'), ('Linux', 'PC - Debian'), ('Serveur', 'Serveur - Permet de deployer les machines virtuelles'), ('Switch', 'Switch - Connecte les serveurs entre eux ')], default='PC', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('num_secu', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('approved', 'APPROVED'), ('pending', 'PENDING'), ('rejected', 'REJECTED')], default='pending', max_length=10)),
                ('maintenanceDate', models.DateTimeField()),
                ('mach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Machine')),
                ('nom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reviews.Personnel')),
            ],
        ),
    ]
