# Generated by Django 2.2.26 on 2022-06-13 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='infra',
            field=models.CharField(choices=[('Siege', 'Poitiers'), ('Filiale', 'Châtellerault')], default='Siege', max_length=20),
        ),
        migrations.AddField(
            model_name='personnel',
            name='infra',
            field=models.CharField(choices=[('Siege', 'Poitiers'), ('Filiale', 'Châtellerault')], default='Siege', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 0, 7, 56, 739171)),
        ),
    ]
