# Generated by Django 2.2.26 on 2022-06-13 08:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220613_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='personnel',
            field=models.CharField(choices=[('Employe', 'Filiale'), ('Manager', 'Siege')], default='Employe', max_length=20),
        ),
        migrations.AlterField(
            model_name='machine',
            name='maintenanceDate',
            field=models.DateField(default=datetime.datetime(2022, 6, 13, 8, 56, 50, 881651)),
        ),
    ]
